### ISSUE TITLE
Create minimal jupyterbook

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/hitchhikers-guide#1]
As a consumer of the `hitchhikers-guide`, I would like to be able to view this information in a Jupyter Book format. To create this, I first need a `_toc.yml` and `_config.yml file`.

From there, a decision needs to be made if this will persistently live somewhere (i.e., GitHub pages, similar to the [elyra workshop](https://aicoe.github.io/elyra-aidevsecops-tutorial/README.html)) or if it will be spawned via Meteor. 
If we want the former, we will need to follow these instructions for the Jupyter Book on Git. The latter only will need the `_toc.yml` and `_config.yml` files to be created. 

WDYT?

**Comment by tumido** [comment]
Hey @isabelizimm ! I like your thinking :slightly_smiling_face: Yes, that's precisely what we want to do! But we want to do even more with this!

The idea started from https://github.com/operate-first/support/issues/326 so some details are in there, but let me try summarize it here:

1. All tutorials and guides that we have for Operate First OPS should end up rewritten as Jupyter notebooks in here.
2. The whole repo should be rendered as JupyterBook for a static content guide (either via meteor or GH pages, we don't really care - once we have the book format, we can support both)
3. The whole repo should be spawneable via Meteor to JupyterHub (with the toolbox installed) - so users can actually execute the Jupyter notebooks and do the Ops as "self service" and open PRs against Operate First directly from JupyterLab

@mimotej  is working on a scaffold while using the "PVC resize" as the initial use case/tutorial/guide in #2. Once we have that PR in we can start thinking about filling in the blanks and actually start trying to deploy it. :slightly_smiling_face:

**Comment by isabelizimm** [comment]
Sounds great! I'm happy to help build this out as it develops👏
