### ISSUE TITLE
Deploy Hitchhiker's guide

### ISSUE THREAD

**Issue by mimotej** [operate-first/hitchhikers-guide#112]
Issue hub for tracking progress on deployment of Hitchhiker's guide and migrating jobs from Travis:
- [x] Decide what is best service to do periodical jobs (GitHub actions, Prow...)
- [x] Migrate from Travis to new service https://github.com/operate-first/operate-first.github.io/pull/333
- [x] Prepare deployment of Hitchhiker's guide via GitHub Actions https://github.com/operate-first/hitchhikers-guide/pull/116
- [ ] Create persistent URL of Hitchhieker's guide
- [ ] URL is linked from https://www.operate-first.cloud/
- [ ] Hitchhiker's guide is deployed via meteor

Related Issues:
https://github.com/operate-first/operate-first.github.io/issues/326

**Comment by durandom** [comment]
How is this related to https://github.com/operate-first/apps/pull/1366 ?

**Comment by mimotej** [comment]
> How is this related to [operate-first/apps#1366](https://github.com/operate-first/apps/pull/1366) ?

In this issue I merged two problems together Migrating Operate First website from Travis https://github.com/operate-first/operate-first.github.io/issues/326, which is done, and Deploying HG as a static website. The second I set out to do a month ago and I didnt manage to keep up with fast changes, that are currently happening with documentation. That lead to creating this PR https://github.com/operate-first/hitchhikers-guide/pull/116. So since there is big disscussion happening here: https://github.com/operate-first/SRE/issues/424 and big changes are introduced here: https://github.com/operate-first/apps/pull/1366. I think this PR (https://github.com/operate-first/hitchhikers-guide/pull/116) is no longer needed.
That means I will propably close that PR and leave the work on docs for now since it would be really hard for me to keep up with changes.
WDYT @tumido @HumairAK
