### ISSUE TITLE
Homepage "I want to learn SRE practices" link is broken

### ISSUE THREAD

**Issue by jeremyeder** [operate-first/hitchhikers-guide#118]
Links here and fails:  https://www.operate-first.cloud/hitchhikers-guide/operations-intro.md

![image](https://user-images.githubusercontent.com/1919640/145051077-2e906e1b-c0df-4b7f-9aef-10793bfb63c3.png)

**Comment by schwesig** [comment]
## What happens
1. goto [https://www.operate-first.cloud/][startpage]
2. click on "I want to learn SRE practices" --> [https://www.operate-first.cloud/hitchhikers-guide/operations-intro.md][learnSRE]
3. Error 404: "Not Found - You just hit a route that doesn't exist... the sadness."

## What was expected
The .md/webpage with a tutorial.

## Ideas to Fix
- [ ] Redirect link to a **different/working URL**
OR
- [ ] Write a new/Edit [**/hitchhikers-guide/operations-intro.md**][learnSRE]

## Screenshots
Step2
![image](https://user-images.githubusercontent.com/89909507/145212386-5e5266aa-0a67-452b-8b9f-007848b2fea8.png)

Step3
![image](https://user-images.githubusercontent.com/89909507/145212561-ba4524bb-5d92-4994-acca-4e8d647ab11d.png)


[startpage]: https://www.operate-first.cloud/
[learnSRE]: https://www.operate-first.cloud/hitchhikers-guide/operations-intro.md

**Comment by schwesig** [comment]
@jeremyeder Thanks for letting us know.

**Comment by schwesig** [comment]
@HumairAK @hemajv

**Comment by schwesig** [comment]
Problem solved
Link was changed
from
https://www.operate-first.cloud/hitchhikers-guide/operations-intro.md
to
https://www.operate-first.cloud/open-source-developers

- [ ] what PR did solve this?
