### ISSUE TITLE
Decide on a demo application that will be used in the SRE demo

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/hitchhikers-guide#86]

**Comment by tumido** [comment]
Demo:

1. Web service with a button
2. On click the webservice inflates memory usage and gets OOMKilled
3. Have a PodMonotor tracking this 
4. Alert on crashloop and/or pod crashing
5. Up the memory limit
6. Observe the service to recover

**Comment by 4n4nd** [comment]
@Gregory-Pereira made some progress here: https://github.com/Gregory-Pereira/SRE-Demo-App

**Comment by HumairAK** [comment]
Alert for the app needs to either link a runbook, or we need to at the least have a runbook to resolve the alert. So if it's a full pvc, we should have a runbook that instructs on how to resize the pvc to have more storage.

**Comment by tumido** [comment]
Solved.
